[tool.poetry]
name = "xingyubot"
version = "0.1.0"
description = ""
authors = ["威立 <66502303+willy1236@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
py-cord = "^2.5.0"
requests = "^2.31.0"
feedparser = "^6.0.11"
pandas = "^2.2.1"
psutil = "^5.9.8"
beautifulsoup4 = "^4.12.3"
mysql-connector-python = "^8.3.0"
genshin = "^1.6.2"
gitpython = "^3.1.43"
apscheduler = "^3.10.4"
fastapi = "^0.110.1"
uvicorn = "^0.29.0"
yt-dlp = "^2024.3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
