[tool.poetry]
name = "discord-helper"
version = "0.1.0"
description = ""
authors = ["willy1236"]
readme = "README.md"
packages = [{include = "discord_helper"}]

[tool.poetry.dependencies]
python = "^3.11"
py-cord = "^2.4.1"
requests = "^2.31.0"
youtube_dl = "^2021.12.17"
mysql-connector-python = "^8.1.0"
GitPython = "^3.1.32"
APScheduler = "^3.10.1"
fastapi = "^0.100.0"
uvicorn = "^0.23.1"
mcrcon = "^0.7.0"
twitchio = "^2.6.0"
beautifulsoup4 = "^4.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
